



export const LOADING = "LOADING"
export const ERROR = "ERROR"
export const CHANGE_VALUE = "CHANGE_VALUE"
export const DO_LOGIN_SUCCESS = "DO_LOGIN_SUCCESS"
export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS"
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS"
export const CONTACT_US = "CONTACT_US"
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS"
export const GET_PACKAGES_SUCCESS = "GET_PACKAGES_SUCCESS"
export const GET_SETTINGS = "GET_SETTINGS"



// 

export const GET_USERS = "GET_USERS"

